import Head from 'next/head'
import axios from 'axios'
import { useState } from 'react';

export default function Home() {

  const [city, setCity] = useState("");
  const [temp, setTemp] = useState(0);

  const api_key = "ae0f36d9196d33d6a617cbc29fa3fc1d";

  const submitForm = (e) => {
    e.preventDefault();
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${api_key}&units=metric`;

    axios.get(url).then((res) => {
      console.log(res);
      setTemp(res.data.main.temp);
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="absolute w-full h-full bg-center bg-cover bg-no-repeat bg-[url('/img/weather-bg.webp')] blur-sm"></div>
    <div className="relative z-10 p-4">
        <div className="box">
            <form onSubmit={submitForm} className="weather-form">
              <label htmlFor="city">City name: </label>
              <input
                type="text"
                id="city"
                placeholder="Type a city"
                value={city}
                onChange={(e) => setCity(e.target.value)}
              />
              <button className="weather-button">Get temperature</button>
            </form>
            <div className="temp">{temp} &#8451;</div>
        </div>
    </div>


    </>
  )
}
