import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react';
import SearchBar from '@/components/SearchBar';
import React from 'react';
import getFormattedWeatherData from '@/components/WeatherService';
import Description from '@/components/Description';

export default function Home() {

  const [weather, setWeather] = useState(null)
  const [units, setUnits] = useState('metric')
  const [city , setCity] = useState('Helsinki')

  useEffect(() => {
    const fetchWeatherData = async () => {
      try {
        const data = await getFormattedWeatherData(city, units);
        console.log(data);
        setWeather(data);
      } catch (error) {
        console.log(error);
      }
      console.log(process.env.API_KEY);

    };
    fetchWeatherData();
    }, [city,units])

    const handleUnitsChange = (e) => {
      setUnits(units === 'metric' ? 'imperial' : 'metric');
    }

 const enterKeyPressed = (e) => {
    if (e.key === 'Enter') {
      setCity(e.target.value)
    }
  }


  return (
    <>
      <Head>
        <title>Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="absolute w-full h-full bg-center bg-cover bg-no-repeat bg-[url('/img/weather-background.png')]"></div>
    <div className="relative z-10 p-4 md:w-1/3 w-full h-screen backdrop-blur-lg">

    <div class="relative flex items-center w-full h-12 rounded-lg focus-within:shadow-lg bg-white overflow-hidden">
        <div class="grid place-items-center h-full w-12 text-gray-300">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
        </div>

        <input
        class="peer h-full w-full outline-none text-sm text-gray-700 pr-2"
        onKeyDown={enterKeyPressed}
        placeholder="Helsinki..." /> 
        <button
        className='py-3 px-5 text-white font-semibold rounded-lg hover:shadow-lg transition duration-3000 cursor-pointer'
         onClick={handleUnitsChange}>
          
          
          {`°${units === 'metric' ? 'F' : 'C'}`}
         </button>
    </div>
              {
                weather && (
                  <div className='text-white'>
                    <h1 className='text-white'>{ `${weather.temp} °${units === 'metric' ? 'C' : 'F'}`}</h1>
                    <h3>{`${weather.name}, ${weather.country}`}</h3>
                    <img src={weather.iconURL
                    } alt="weather icon" />
                    <h1>{weather.description}</h1>
                    <Description weather={weather} units={units} />
                  </div>
                )
              }
        </div>


    </>
  )
}
